### ISSUE TITLE
Feature Request: Additional fn signature for React's useAtom to return focused [value, updater]

### ISSUE THREAD

**Issue by is-jonreeves** [xoidlabs/xoid#20]
I was wondering if you might consider extending the `useAtom` hook to take a `focusSelector: string | function` as an optional second parameter. It might provide a familiar syntax for those migrating away from `useState`, and reduce down on the number of variables you need to name and maintain. As an example, this is a simple wrapper illustrating the point...

```ts
// Hook
const useAtomWrapper = (atom, selector) => {
  const result = selector ? atom.focus(selector) : atom;
  return [ useAtom(result), result.update ];
}
```

```ts
// Usage
const Component = () => {
  const $state = useSetup(() => create({ count: 0, theme: 'dark' }));

  const [ count, setCount ] = useAtomWrapper($state, 'count');
  const [ theme, setTheme ] = useAtomWrapper($state, s => s.theme);

  return <button className={theme} onClick={() => setCount(v => v+1)}>{count}</button>;
}
```

Without the above convenience wrapper, I found myself needing to produce a lot of similarly named intermediate Atoms and it wasn't always instinctive which to read from and which to update with unless you are really careful with your naming. For example:
```ts
const Component = () => {
  const $state = useSetup(() => create({ count: 0, theme: 'dark' }));

  const $count = $state.focus('count');
  const $theme = $state.focus(s => s.theme);

  const count = useAtom($count);
  const theme = useAtom($theme);

  return <button className={theme} onClick={() => $count.update(v => v+1)}>{count}</button>;
}
```

Would love to know your thoughts on this.

Cheers,
Jon

**Comment by onurkerimov** [comment]
Hi @is-jonreeves , thank you for your valuable feedback!

Why not use the following coding style?
```js
const Component = () => {
  const $state = useSetup(() => create({ count: 0, theme: 'dark' }));
  const { count, theme } = useAtom($state);

  return <button className={theme} onClick={() => $state.focus('count').update(v => v+1)}>{count}</button>;
}
```
I guess inlining `$state.focus('count').update(v => v+1)` could feel too long, but one of the ideas behind xoid was not needing to generate proper names as "setCount", and simply using "$count.set" while working with local state. However I totally understand that it's a matter of preference, and I think that yours is a good suggestion.

However, currently `useAtom`'s second argument is reserved for the following:
```js
const CounterModel = (value: number) =>
  create(value, (atom) => ({
    increment: () => atom.update((s) => s + 1),
    decrement: () => atom.update((s) => s - 1),
  }))

const [count, { increment, decrement }] = useAtom(() => CounterModel(0), true)
```
This can be considered as a shorthand for:
```js
const $counter = useSetup(() => CounterModel(0))
const count = useAtom($counter)
const { increment, decrement } = $counter.actions
```
A few latest beta versions of `@xoid/react` have this feature. Back then I wasn't sure of this feature, so I didn't document this anywhere, but I'll document it soon.
